In [79]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [80]:
#Load the dataset
df=pd.read_csv('Churn_Modelling.csv')

In [81]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [82]:
##Preprocess the data
##Delete the irrelevant col
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [83]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [84]:
#Encoding
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])

In [85]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [86]:
#One hot encoding
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
geo_encoded=ohe.fit_transform(df[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [87]:
geo_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [88]:
ohe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [89]:
geo_encoded_df=pd.DataFrame(geo_encoded.toarray(),columns=ohe.get_feature_names_out(['Geography']))

In [90]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [91]:
##Combine both of them
df=pd.concat([df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [92]:
df

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [93]:
##Save the encoder for the further use
## Save the encoders and sscaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(ohe,file)

In [94]:
## DiVide the dataset into indepent and dependent features
X=df.drop('Exited',axis=1)
y=df['Exited']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [95]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [96]:
##ANN Implementation
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [97]:
X_train.shape[1]

12

In [98]:
#Build our ANN Model
model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)), #HL1 Connected with input layer
        Dense(32,activation='relu'),  #HL2
        Dense(1,activation='sigmoid') #Output Layer
    ]
)

In [99]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [100]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [101]:
##Compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [102]:
##Set up the tensorflow 
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [103]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [104]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 0s 704us/step - loss: 0.3954 - accuracy: 0.8326 - val_loss: 0.3678 - val_accuracy: 0.8580
Epoch 2/100
250/250 [==============================] - 0s 471us/step - loss: 0.3580 - accuracy: 0.8506 - val_loss: 0.3471 - val_accuracy: 0.8565
Epoch 3/100
250/250 [==============================] - 0s 472us/step - loss: 0.3490 - accuracy: 0.8590 - val_loss: 0.3506 - val_accuracy: 0.8625
Epoch 4/100
250/250 [==============================] - 0s 465us/step - loss: 0.3456 - accuracy: 0.8583 - val_loss: 0.3402 - val_accuracy: 0.8620
Epoch 5/100
250/250 [==============================] - 0s 468us/step - loss: 0.3383 - accuracy: 0.8616 - val_loss: 0.3470 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 0s 471us/step - loss: 0.3370 - accuracy: 0.8629 - val_loss: 0.3433 - val_accuracy: 0.8580
Epoch 7/100
250/250 [==============================] - 0s 460us/step - loss: 0.3355 - accuracy: 0.8636 - val_loss: 0.3479 - val_accuracy: 0.8550
Epoch 8/100
250/250 [==============================] - 0s 474us/step - loss: 0.3355 - accuracy: 0.8641 - val_loss: 0.3354 - val_accuracy: 0.8600
Epoch 9/100
250/250 [==============================] - 0s 481us/step - loss: 0.3314 - accuracy: 0.8658 - val_loss: 0.3489 - val_accuracy: 0.8565
Epoch 10/100
250/250 [==============================] - 0s 481us/step - loss: 0.3280 - accuracy: 0.8650 - val_loss: 0.3430 - val_accuracy: 0.8615
Epoch 11/100
250/250 [==============================] - 0s 484us/step - loss: 0.3276 - accuracy: 0.8651 - val_loss: 0.3613 - val_accuracy: 0.8595
Epoch 12/100
250/250 [==============================] - 0s 463us/step - loss: 0.3291 - accuracy: 0.8649 - val_loss: 0.3487 - val_accuracy: 0.8580
Epoch 13/100
250/250 [==============================] - 0s 471us/step - loss: 0.3261 - accuracy: 0.8671 - val_loss: 0.3467 - val_accuracy: 0.8585
Epoch 14/100
250/250 [==============================] - 0s 463us/step - loss: 0.3222 - accuracy: 0.8694 - val_loss: 0.3518 - val_accuracy: 0.8610
Epoch 15/100
250/250 [==============================] - 0s 469us/step - loss: 0.3203 - accuracy: 0.8656 - val_loss: 0.3495 - val_accuracy: 0.8550
Epoch 16/100
250/250 [==============================] - 0s 465us/step - loss: 0.3195 - accuracy: 0.8684 - val_loss: 0.3516 - val_accuracy: 0.8520
Epoch 17/100
250/250 [==============================] - 0s 467us/step - loss: 0.3154 - accuracy: 0.8677 - val_loss: 0.3590 - val_accuracy: 0.8505
Epoch 18/100
250/250 [==============================] - 0s 463us/step - loss: 0.3143 - accuracy: 0.8708 - val_loss: 0.3555 - val_accuracy: 0.8565

In [105]:
model.save('model.h5')

/Users/jalshah/Desktop/Machine_Learning/Deep Learning/.venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [106]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [107]:
%tensorboard --logdir logs/fit

ERROR: Timed out waiting for TensorBoard to start. It may still be running as pid 11094.